### ISSUE TITLE
Document versoning

### ISSUE THREAD

**Issue by manosbatsis** [corda/token-sdk#145]
Apologies for being lazy, please correct me if i'm wrong bellow:

- SNAPSHOT versions are not updated at this time
- RC versions are in their place, i.e. new artifacts overwrite the version

If i'm wrong please point the way. and close.

If not, is there a reason for not rolling out SNAPSHOTS between RCs? Mavens might be an expensive conversion to break  if only to reuse the release pipeline; There's lots of infrastructure and humans out there  to miss RC is a SNAPSHOT, with reproducible builds pulled under them. Even after figuring out, would one i be able to retrieve the right version? Repo plumbing out there might fail to maintain past revisions for a  seemingly non-snapshot without complaints.

**Comment by roger3cev** [comment]
Yes that's right. We don't overwrite RCs though, unless there's a dumb error that needs immediately fixing.

We definitely can roll out SNAPSHOTs and indeed we do this for the Corda binaries it's just that we haven't got round to doing it for tokens yet. Will keep you updated 👍
