### ISSUE TITLE
Error when moving an evolvable token

### ISSUE THREAD

**Issue by adelRestom** [corda/token-sdk#146]
* Corda OS 4.3-RC01  
* Tokens 1.1-RC01  

Here's the sequence of events:  
1. Create EvolvableTokenType  
2. Issue a token of that type to a node  
3. Move part of that amount to a new node  

I get the following error:  
```
com.r3.corda.lib.tokens.selection.InsufficientBalanceException: Insufficient spendable states identified for 0.000001 TokenPointer(class xxx, defcb428-a1f6-4765-9241-1a9ee5f703b1) issued by xxx.	at com.r3.corda.lib.tokens.selection.database.selector.DatabaseTokenSelection.selectTokens(DatabaseTokenSelection.kt:140) ~[tokens-selection-1.1-RC01.jar:?]
```

As you can see from the picture below, I issued 10, the balance of the node is 10, I created an amount of 1 which I used in the move flow.

![Capture](https://user-images.githubusercontent.com/37046080/67707216-1550dc00-f988-11e9-93bd-87820067a08c.PNG)

**Comment by adelRestom** [comment]
So to confirm that this is not something related to my work (i.e. custom flows); I used the Java template (token-template branch) and got the same error, the template uses older version of Corda and tokens SDK (4.1 and 1.0) so I guess this problem is old? I had to create a new package `token` under `com.template` and move `states` and `ExampleEvolvableTokenTypeContract` under it in order to write the below test.

**Comment by adelRestom** [comment]
[FlowTests.txt](https://github.com/corda/token-sdk/files/3780354/FlowTests.txt)

**Comment by adelRestom** [comment]
For the older tokens SDK version the error is:
```
java.lang.IllegalStateException: Insufficient spendable states identified for 1 TokenPointer(class com.template.token.states.ExampleEvolvableTokenType, 0be9ae38-3047-4431-a506-228dbb6a0a7d) issued by Mock Company 1.
	at com.r3.corda.lib.tokens.workflows.internal.selection.TokenSelection.attemptSpend(TokenSelection.kt:143) ~[tokens-workflows-1.0.jar:?]
```

**Comment by roger3cev** [comment]
Thanks @adelRestom - we'll look into this and get back to you

**Comment by coderguy1998** [comment]
When I was implementing the dollar-to-house-token sample project using Kotlin I have got the same error and I'm not able to resolve it.
