### ISSUE TITLE
java.lang.SecurityException at FlowTests.kt in corda-template-kotlin

### ISSUE THREAD

**Issue by rajeshso** [corda/token-sdk#147]
I am following the documentation in https://github.com/corda/token-sdk to get the build and test the corda template. The ./gradlew test results in an error as this :
`> Task :workflows:test

com.template.ContractTests > dummy test FAILED
    java.lang.SecurityException at ContractTests.kt:7

com.template.FlowTests > dummy test FAILED
    java.lang.SecurityException at FlowTests.kt:9`

I want to jumpstart on using the token-sdk but could not progress further

**Comment by roger3cev** [comment]
What version of Java are you using and on what platform?
