### ISSUE TITLE
Hibernate infers incorrect column type for token_class on Azure SQL

### ISSUE THREAD

**Issue by mplatt** [corda/token-sdk#150]
Hibernate infers the type `varchar(255)` for the fields `PersistentFungibleToken.tokenClass` and `PersistentNonFungibleToken.tokenClass`. The Liquibase migration script creates both columns as `NVARCHAR(255)`. This leads to the following exception when starting Corda with Token SDK 1.0 deployed after executing the migration.
This has been observed when connecting to an Azure SQL database using the `mssql-jdbc-6.2.2.jre8.jar` driver.

```
[ERROR] 17:52:52+0000 [main] internal.NodeStartupLogging.invoke - Exception during node startup: Incompatible schema change detected. Please run the node with database.initialiseSchema=true. Reason: Schema-validation: wrong column type encountered in column [token_class] in table [schem.fungible_token]; found [nvarchar (Types#NVARCHAR)], but expecting [varchar(255) (Types#VARCHAR)] [errorCode=bdopq4, moreInformationAt=https://errors.corda.net/ENT/4.1/bdopq4]
```

**Potential Fixes**

1. Provide a type hint to Hibernate by annotating `PersistentFungibleToken.tokenClass` and `PersistentNonFungibleToken.tokenClass` with `@Type(type = "org.hibernate.type.StringNVarcharType")`.
2. Provide database migrations (_fungible-token-schema-v2.changelog-master.xml_, _non-fungible-token-schema-v2.changelog-master.xml_) that change the type of `token_class` to `varchar`.

**Caveats**

Approach 1 does not work inside the `contracts` sub project when built in deterministic mode as `org.hibernate` is not available in a dJVM context. 
`NonFungibleTokenSchema` and `FungibleTokenSchema` cannot easily be moved to the `workflows` sub project (where `org.hibernate` is available).

Approach 2 requires a migration of a column to a different data type.

**Comment by roger3cev** [comment]
Hey @mplatt did you manage to fix this? Is it worth raising a PR? Cheers dude

**Comment by mplatt** [comment]
Not for 1.1, as the approach does not work inside the contracts sub project when it is built in deterministic mode. `org.hibernate` is not available in a dJVM context.
I could create a patch for 1.1 but I couldn't figure out which branch to PR against.

**Comment by kasiastreich** [comment]
We spoke about on Slack, we put all fixes to master and they will be released in 1.1. Could you he issue with hibernate? Because we have our schemas in the contracts project and it works fine

**Comment by mplatt** [comment]
Thanks. I'm aware of the conversation. As described in the report above,
the fix I propose is not applicable to 1.1, meaning the change would not
compile on master.

**Comment by kasiastreich** [comment]
Sorry I commented by accident, before I read the caveats of the report :)

**Comment by kasiastreich** [comment]
Fixed in https://github.com/corda/token-sdk/pull/160 (waiting for QA to test extensively).
