### ISSUE TITLE
Error Redeeming self-issued Fungible Tokens

### ISSUE THREAD

**Issue by TywinLannister1313** [corda/token-sdk#162]
Operating System: Windows 10
Corda: 4.3
tokens_release_version = '1.1-RC05-PRESIGN'
Testing with a MockNetwork

I have been testing token-sdk and I stumbled into an error.  It’s probably something I am doing wrong but I thought I would post it here just in case.

I’m getting the error when a Party issues FungibleTokens to itself and then redeems them using initiating flow `RedeemFungibleTokens`:

`return subFlow(new RedeemFungibleTokens(amount, issuer, observers));`

If I examine the vault the redeem seems to work as the FungibleTokens are consumed.  All my other redeems work where the Tokens are directly issued to a second party and then redeemed.  Or if the issuer issues Fungible Tokens to themselves, moves the tokens to a second Party and then that Party redeems them. I get the same error with our without observers.

I am going to test the inline redeem next : `RedeemFungibleTokensFlow()`

Let me know if I can provide any other information.

Here is the error:

[INFO] 16:28:56,442 [Mock network] corda.flow. - Flow raised an error: Tried to access ended session SessionId(toLong=-5509191397927053834) with empty buffer. Sending it to flow hospital to be triaged. {fiber-id=10000017, flow-id=ab81366b-47b7-47e1-b30c-704143e33af7, invocation_id=d2fdc33a-f1b7-4f0a-a3d6-dd0d2fb7c8b1, invocation_timestamp=2019-12-03T23:28:55.424Z, origin=O=Federal Reserve, L=New York City, C=US, session_id=d2fdc33a-f1b7-4f0a-a3d6-dd0d2fb7c8b1, session_timestamp=2019-12-03T23:28:55.424Z, thread-id=829}

[INFO] 16:28:56,445 [Mock network] statemachine.StaffedFlowHospital. - Flow [ab81366b-47b7-47e1-b30c-704143e33af7] admitted to hospital in state StateMachineState(checkpoint=Checkpoint(invocationContext=InvocationContext(origin=Peer(party=O=Federal Reserve, L=New York City, C=US), trace=Trace(invocationId=d2fdc33a-f1b7-4f0a-a3d6-dd0d2fb7c8b1, timestamp: 2019-12-03T23:28:55.424Z, entityType: Invocation, sessionId=d2fdc33a-f1b7-4f0a-a3d6-dd0d2fb7c8b1, timestamp: 2019-12-03T23:28:55.424Z, entityType: Session), actor=null, externalTrace=null, impersonatedActor=null), ourIdentity=O=Federal Reserve, L=New York City, C=US, sessions={SessionId(toLong=-5509191397927053834)=Initiated(peerParty=O=Federal Reserve, L=New York City, C=US, peerFlowInfo=FlowInfo(flowVersion=1, appName=tokens-workflows-1.1-RC05-PRESIGN), receivedMessages=[], initiatedState=Ended, errors=[], deduplicationSeed=D-6749170431553071374-6281469155197028627)}, subFlowStack=[Inlined(flowClass=class com.r3.corda.lib.tokens.workflows.flows.rpc.RedeemFungibleTokensHandler, subFlowVersion=CorDappFlow(platformVersion=5, corDappName=tokens-workflows-1.1-RC05-PRESIGN, corDappHash=1E6A18A16B476D6898C230A44392385A326754A023F6304484CC7115E6C5F16B), isEnabledTimedFlow=false)], flowState=Started(flowIORequest=Receive(sessions=[FlowSessionImpl(destination=O=Federal Reserve, L=New York City, C=US, sourceSessionId=SessionId(toLong=-5509191397927053834))]), frozenFiber=4FB0427091DDBFE448DED701C5C01B9F8F5CD6C08BC9E0241D295838A217E360), errorState=Clean, numberOfSuspends=5), flowLogic=com.r3.corda.lib.tokens.workflows.flows.rpc.RedeemFungibleTokensHandler@4f79df95, pendingDeduplicationHandlers=[net.corda.testing.node.internal.MockNodeMessagingService$InMemoryDeduplicationHandler@77eae423], isFlowResumed=true, isTransactionTracked=false, isAnyCheckpointPersisted=true, isStartIdempotent=false, isRemoved=false, senderUUID=caea3be1-72d0-41e6-ae62-e39b141ea180) {fiber-id=10000017, flow-id=ab81366b-47b7-47e1-b30c-704143e33af7, invocation_id=d2fdc33a-f1b7-4f0a-a3d6-dd0d2fb7c8b1, invocation_timestamp=2019-12-03T23:28:55.424Z, origin=O=Federal Reserve, L=New York City, C=US, session_id=d2fdc33a-f1b7-4f0a-a3d6-dd0d2fb7c8b1, session_timestamp=2019-12-03T23:28:55.424Z, thread-id=829}

[INFO] 16:28:56,448 [Mock network] statemachine.StaffedFlowHospital. - Error 1 of 1: {fiber-id=10000017, flow-id=ab81366b-47b7-47e1-b30c-704143e33af7, invocation_id=d2fdc33a-f1b7-4f0a-a3d6-dd0d2fb7c8b1, invocation_timestamp=2019-12-03T23:28:55.424Z, origin=O=Federal Reserve, L=New York City, C=US, session_id=d2fdc33a-f1b7-4f0a-a3d6-dd0d2fb7c8b1, session_timestamp=2019-12-03T23:28:55.424Z, thread-id=829}

 net.corda.core.flows.UnexpectedFlowEndException: Tried to access ended session SessionId(toLong=-5509191397927053834) with empty buffer

**Comment by TywinLannister1313** [comment]
Just to clarify - I am calling RedeemFungibleTokens():

`return subFlow(new RedeemFungibleTokens(amount, issuer, observers));`

**Comment by TywinLannister1313** [comment]
I tested inlined fungible token flows `RedeemFungibleTokensFlow`/`RedeemTokensFlowHandler`.  

If Party A issues FungibleTokens to itself and then Party A redeems those tokens I get the same error:

_net.corda.core.flows.UnexpectedFlowEndException: Tried to access ended session SessionId(toLong=-4589550737635421977) with empty buffer_

Despite the error the vault shows that the redeem was successful.

**Comment by kasiastreich** [comment]
Hey, thanks for that, I suspect that this is an actual an error with session messages not being aligned properly for redeem flow, because finality flow treats sessions with yourself in a special way. Good catch! I will get that fixed

**Comment by roger3cev** [comment]
Thanks both!

**Comment by kasiastreich** [comment]
https://github.com/corda/token-sdk/pull/167

**Comment by roger3cev** [comment]
Thanks @kasiastreich. @TywinLannister1313 see Kasia's PR above, which fixes this issue. Thanks for raising!
