### ISSUE TITLE
LocalTokenSelector has no generateMove function

### ISSUE THREAD

**Issue by jarturocastan** [corda/token-sdk#163]
Hi, I try to use in memory tokens, but  the class LocalTokenSelector  has no generateMove fuction , I use token sdk 1.1-RC05-PRESIGN

**Comment by jarturocastan** [comment]
This is my code : 

       val notary =  serviceHub.networkMapCache.notaryIdentities.first()
            val transactionBuilder = TransactionBuilder(notary = notary)

            //Configuración
            val uuid = UUID.fromString(id)
            val queryCriteria = QueryCriteria.LinearStateQueryCriteria(null, ImmutableList.of(uuid), null,
                    Vault.StateStatus.UNCONSUMED, null)
            val tokenStateAndRef = serviceHub.vaultService.queryBy<RealEstateEvolvableTokenType>(queryCriteria).states.single()
            val tokenMXN = tokenStateAndRef.state.data.toPointer<RealEstateEvolvableTokenType>()
            val amount = Amount(quantity,tokenMXN);
            val partyAndAmount = PartyAndAmount(holder,amount)

            val participants = listOf(partyAndAmount).map(PartyAndAmount<*>::party)
            var observerSessions : List<FlowSession>;
            val participantSessions = sessionsForParties(participants)

            val localTokenSelector = LocalTokenSelector(serviceHub);
            val changeHolder = serviceHub.keyManagementService.freshKeyAndCert(ourIdentityAndCert, false).party.anonymise()
            if(holder.equals(auditor)) {
                observerSessions = emptyList()
            } else {
                observerSessions = sessionsForParties(listOf(auditor))
            }
            val (inputs, outputs) =  localTokenSelector.generateMove(
                    lockId = runId.uuid,
                    partyAndAmounts = listOf(partyAndAmount as PartyAndAmount<TokenType>),
                    changeHolder = changeHolder
            )

            val flow = subFlow(MoveTokensFlow(inputs, outputs, participantSessions,observerSessions))
            addMoveTokens(transactionBuilder, inputs, outputs)

**Comment by kasiastreich** [comment]
Hi, the method is on the Selector abstract class that is super class of LocalTokenSelector. Probably the issue will go away after invalidating caches and refreshing gradle. Let me know if you still see the problem!

**Comment by jarturocastan** [comment]
thank you for you help it was the cache

**Comment by roger3cev** [comment]
Cheers!
