### ISSUE TITLE
Hi, I have this problem when I try to move tokens through partys, net.corda.core.flows.UnexpectedFlowEndException: O=PartyB, L=New York, C=US has finished prematurely and we're trying to send them the finalised transaction. Did they forget to call ReceiveFinalityFlow? 

### ISSUE THREAD

**Issue by jarturocastan** [corda/token-sdk#165]
Hi, I have this problem when I try to move tokens from PartyA to Party B, this is the complete exception
[INFO ] 2019-12-11T00:55:12,869Z [Node thread-1] statemachine.StaffedFlowHospital. - Flow [7cbcd75e-cf2a-4ec7-af07-17d042c31eb6] admitted to hospital in state StateMachineState(checkpoint=Checkpoint(invocationContext=InvocationContext(origin=RPC(actor=Actor(id=Id(value=user1), serviceId=AuthServiceId(value=NODE_CONFIG), owningLegalIdentity=O=PartyA, L=London, C=GB)), trace=Trace(invocationId=f562f3be-2754-4305-88ce-44641180b4d9, timestamp: 2019-12-11T00:55:12.454Z, entityType: Invocation, sessionId=8ea73c87-beb7-4a97-9b34-225e44f68c9f, timestamp: 2019-12-11T00:50:13.011Z, entityType: Session), actor=Actor(id=Id(value=user1), serviceId=AuthServiceId(value=NODE_CONFIG), owningLegalIdentity=O=PartyA, L=London, C=GB), externalTrace=null, impersonatedActor=null), ourIdentity=O=PartyA, L=London, C=GB, sessions={SessionId(toLong=-8865563624912587074)=Uninitiated(destination=O=PartyB, L=New York, C=US, initiatingSubFlow=Initiating(flowClass=class com.template.flows.MoveFungibleTokenFlow, classToInitiateWith=class com.template.flows.MoveFungibleTokenFlow, flowInfo=FlowInfo(flowVersion=1, appName=workflows-0.1), subFlowVersion=CorDappFlow(platformVersion=5, corDappName=workflows-0.1, corDappHash=313CBD335D3B29B3146FC37ACF5EB638F6C956DBE36EF9174C7A42E2065FB767), isEnabledTimedFlow=false), sourceSessionId=SessionId(toLong=-8865563624912587074), additionalEntropy=-7645822736075215682), SessionId(toLong=-5309249725331446777)=Initiated(peerParty=O=PartyB, L=New York, C=US, peerFlowInfo=FlowInfo(flowVersion=1, appName=workflows-0.1), receivedMessages=[], initiatedState=Live(peerSinkSessionId=SessionId(toLong=6391133800057730846)), errors=[FlowError(errorId=3432256339453046668, exception=net.corda.core.flows.UnexpectedFlowEndException: Counter-flow errored)], deduplicationSeed=R--5309249725331446777-5204484759134166421), SessionId(toLong=1345013703188110755)=Initiated(peerParty=O=Notary, L=London, C=GB, peerFlowInfo=FlowInfo(flowVersion=5, appName=corda), receivedMessages=[], initiatedState=Live(peerSinkSessionId=SessionId(toLong=8945669728544964326)), errors=[], deduplicationSeed=R-1345013703188110755-8480087332619836515)}, subFlowStack=[Initiating(flowClass=class com.template.flows.MoveFungibleTokenFlow, classToInitiateWith=class com.template.flows.MoveFungibleTokenFlow, flowInfo=FlowInfo(flowVersion=1, appName=workflows-0.1), subFlowVersion=CorDappFlow(platformVersion=5, corDappName=workflows-0.1, corDappHash=313CBD335D3B29B3146FC37ACF5EB638F6C956DBE36EF9174C7A42E2065FB767), isEnabledTimedFlow=false)], flowState=Started(flowIORequest=SendAndReceive({FlowSessionImpl(destination=O=PartyB, L=New York, C=US, sourceSessionId=SessionId(toLong=-5309249725331446777))=FlowSessionImpl(destination=O=PartyB, L=New York, C=US, sourceSessionId=SessionId(toLong=-5309249725331446777))=DD4D28A3E074C470AC7C0A43A36257251F767EDC0FE812601D24E1B6C40B2387}, shouldRetrySend=false), frozenFiber=3EDDE877003693046816913884F70881F306F541E2607314035C9F76793DEB15), errorState=Clean, numberOfSuspends=5), flowLogic=com.template.flows.MoveFungibleTokenFlow@6452e7a5, pendingDeduplicationHandlers=[], isFlowResumed=true, isTransactionTracked=false, isAnyCheckpointPersisted=true, isStartIdempotent=false, isRemoved=false, senderUUID=8c8690e5-68fb-4d9f-98b0-66192a59b429) {actor_id=user1, actor_owning_identity=O=PartyA, L=London, C=GB, actor_store_id=NODE_CONFIG, fiber-id=10000003, flow-id=7cbcd75e-cf2a-4ec7-af07-17d042c31eb6, invocation_id=f562f3be-2754-4305-88ce-44641180b4d9, invocation_timestamp=2019-12-11T00:55:12.454Z, origin=user1, session_id=8ea73c87-beb7-4a97-9b34-225e44f68c9f, session_timestamp=2019-12-11T00:50:13.011Z, thread-id=307, tx_id=BF8511894FDFAAAEA6AB60DD845A78A724D3E9BEBC054D2D9BCC43C70BEE7A8E}
[INFO ] 2019-12-11T00:55:12,869Z [Node thread-1] statemachine.StaffedFlowHospital. - Error 1 of 1: {actor_id=user1, actor_owning_identity=O=PartyA, L=London, C=GB, actor_store_id=NODE_CONFIG, fiber-id=10000003, flow-id=7cbcd75e-cf2a-4ec7-af07-17d042c31eb6, invocation_id=f562f3be-2754-4305-88ce-44641180b4d9, invocation_timestamp=2019-12-11T00:55:12.454Z, origin=user1, session_id=8ea73c87-beb7-4a97-9b34-225e44f68c9f, session_timestamp=2019-12-11T00:50:13.011Z, thread-id=307, tx_id=BF8511894FDFAAAEA6AB60DD845A78A724D3E9BEBC054D2D9BCC43C70BEE7A8E}
net.corda.core.flows.UnexpectedFlowEndException: O=PartyB, L=New York, C=US has finished prematurely and we're trying to send them the finalised transaction. Did they forget to call ReceiveFinalityFlow? (Counter-flow errored)
	at net.corda.core.flows.FinalityFlow.call(FinalityFlow.kt:158) ~[corda-core-4.3-RC02.jar:?]
	at net.corda.core.flows.FinalityFlow.call(FinalityFlow.kt:39) ~[corda-core-4.3-RC02.jar:?]
	at net.corda.node.services.statemachine.FlowStateMachineImpl.subFlow(FlowStateMachineImpl.kt:330) ~[corda-node-4.3-RC02.jar:?]
	at net.corda.core.flows.FlowLogic.subFlow(FlowLogic.kt:320) ~[corda-core-4.3-RC02.jar:?]
	at com.r3.corda.lib.tokens.workflows.internal.flows.finality.ObserverAwareFinalityFlow.call(ObserverAwareFinalityFlow.kt:75) ~[?:?]
	at com.r3.corda.lib.tokens.workflows.internal.flows.finality.ObserverAwareFinalityFlow.call(ObserverAwareFinalityFlow.kt:35) ~[?:?]
	at net.corda.node.services.statemachine.FlowStateMachineImpl.subFlow(FlowStateMachineImpl.kt:330) ~[corda-node-4.3-RC02.jar:?]
	at net.corda.core.flows.FlowLogic.subFlow(FlowLogic.kt:320) ~[corda-core-4.3-RC02.jar:?]
	at com.template.flows.MoveFungibleTokenFlow.call(RealEstateEvolvableFungibleTokenFlow.kt:96) ~[?:?]
	at com.template.flows.MoveFungibleTokenFlow.call(RealEstateEvolvableFungibleTokenFlow.kt:66) ~[?:?]
	at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:270) ~[corda-node-4.3-RC02.jar:?]
	at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:46) ~[corda-node-4.3-RC02.jar:?]
	at co.paralleluniverse.fibers.Fiber.run1(Fiber.java:1092) ~[quasar-core-0.7.10-jdk8.jar:0.7.10]
	at co.paralleluniverse.fibers.Fiber.exec(Fiber.java:788) ~[quasar-core-0.7.10-jdk8.jar:0.7.10]
	at co.paralleluniverse.fibers.RunnableFiberTask.doExec(RunnableFiberTask.java:100) ~[quasar-core-0.7.10-jdk8.jar:0.7.10]
	at co.paralleluniverse.fibers.RunnableFiberTask.run(RunnableFiberTask.java:91) ~[quasar-core-0.7.10-jdk8.jar:0.7.10]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_221]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_221]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) ~[?:1.8.0_221]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:1.8.0_221]
	at net.corda.node.utilities.AffinityExecutor$ServiceAffinityExecutor$1$thread$1.run(AffinityExecutor.kt:63) ~[corda-node-4.3-RC02.jar:?]

And this is the code of my flow 

  class MoveFungibleTokenFlow(
                private val me: Party,
                private val holder: Party,
                private val quantity: Long,
                val auditor : Party) : FlowLogic<SignedTransaction>() {

        override val progressTracker = ProgressTracker()

        @Suspendable
        @Throws(FlowException::class)
        override fun call(): SignedTransaction {
            val notary =  serviceHub.networkMapCache.notaryIdentities.first()
            val transactionBuilder = TransactionBuilder( notary = notary)
            val localTokenSelector = LocalTokenSelector(serviceHub)
            val tokenMXN : TokenType  = FiatCurrency.getInstance("MXN");
            val amount = Amount(quantity,tokenMXN);
            val partiesAndAmounts : List<Pair<AbstractParty, Amount<TokenType>>> = listOf(Pair(holder,amount))
            val session = initiateFlow(holder)
            val (inputs, outputs) = localTokenSelector.generateMove(
                    lockId = transactionBuilder.lockId, // Defaults to FlowLogic.currentTopLevel?.runId?.uuid ?: UUID.randomUUID()
                    partiesAndAmounts  =  partiesAndAmounts,
                    changeHolder = me,
                    queryBy = TokenQueryBy(issuer = ourIdentity, predicate = { it.state.notary == notary })
            )

           addMoveTokens(transactionBuilder, inputs, outputs)
           // subFlow(IdentitySyncFlow.Send(session, transactionBuilder.toWireTransaction(serviceHub)))
            val ourSigningKeys = transactionBuilder.toLedgerTransaction(serviceHub).ourSigningKeys(serviceHub)
            val initialStx = serviceHub.signInitialTransaction(transactionBuilder, signingPubKeys = ourSigningKeys)
            val stx = subFlow(CollectSignaturesFlow(initialStx, listOf(session), ourSigningKeys))
            return subFlow(ObserverAwareFinalityFlow(stx, listOf(session)))
        }
    }

        @InitiatedBy(MoveFungibleTokenFlow::class)
        class MoveFungibleTokenFlowHandler(val otherSession: FlowSession) : FlowLogic<Unit>() {
            @Suspendable
            override fun call() {
                val priceNotification = otherSession.receive<PriceNotification>().unwrap { it }
                val changeHolder = serviceHub.keyManagementService.freshKeyAndCert(ourIdentityAndCert, false).party.anonymise()
                val (inputs, outputs) = LocalTokenSelector(serviceHub).generateMove(
                        lockId = runId.uuid,
                        partiesAndAmounts = listOf(Pair(otherSession.counterparty, priceNotification.amount)),
                        changeHolder = changeHolder
                )
                subFlow(SendStateAndRefFlow(otherSession, inputs))
                otherSession.send(outputs)
               // subFlow(IdentitySyncFlow.Receive(otherSession))
                subFlow(object : SignTransactionFlow(otherSession) {
                    override fun checkTransaction(stx: SignedTransaction) {
                        // We should perform some basic sanity checks before signing the transaction. This step was omitted for simplicity.
                    }
                })
                subFlow(ObserverAwareFinalityFlowHandler(otherSession))
            }
        }
}

**Comment by roger3cev** [comment]
Thanks for raising this. It might be a bug. @kasiastreich was going to look into it. Cheers

**Comment by jarturocastan** [comment]
Ok thank you

**Comment by kasiastreich** [comment]
Hi, looking at your code your send and receives don't align. For instance in `MoveFungibleTokenFlowHandler` you call:
```subFlow(SendStateAndRefFlow(otherSession, inputs))
otherSession.send(outputs)```

but nowhere in the `MoveFungibleTokenFlow` matching subflow/receive is called.
Hope that helps.

**Comment by jarturocastan** [comment]
Hi, I develop with any inmemory configuration and I get the same error, with this flow 

    @StartableByRPC
    class IssueEvolvableFungibleTokenFlow(
            private val quantity: Double,
            private val holder: Party) : FlowLogic<SignedTransaction>() {

        override val progressTracker = ProgressTracker()

        @Suspendable
        @Throws(FlowException::class)
        override  fun call(): SignedTransaction {
            val tokenMXN : TokenType  = FiatCurrency.getInstance("MXN");
            val token : IssuedTokenType = tokenMXN issuedBy  ourIdentity;
            val cantidad = quantity of token;
          val fungibleToken = FungibleToken(cantidad,holder);
           return subFlow(IssueTokens(listOf(fungibleToken)))
        }

    }

    @StartableByRPC
    class MoveEvolvableFungibleTokenFlow(
                private val holder: Party,
                private val quantity: Double,
                val auditor : Party) : FlowLogic<SignedTransaction>() {

        override val progressTracker = ProgressTracker()

        @Suspendable
        @Throws(FlowException::class)
        override fun call(): SignedTransaction {
            val tokenMXN : TokenType  = FiatCurrency.getInstance("MXN");
            val amount = Amount(quantity.toLong(),tokenMXN);
            val partyAndAmount = PartyAndAmount(holder,amount)
            if(holder.equals(auditor) || ourIdentity.equals(auditor)) {
                return subFlow(MoveFungibleTokens(partyAndAmount = partyAndAmount))
            } else {
                return subFlow(MoveFungibleTokens(partyAndAmount = partyAndAmount, observers = listOf(auditor)))
            }
        }
    }


This is the error
{
  "timestamp": "2019-12-11T21:17:05.230Z",
  "status": 500,
  "error": "Internal Server Error",
  "message": "net.corda.core.flows.UnexpectedFlowEndException: O=Banorte, L=New York, C=US has finished prematurely and we're trying to send them the finalised transaction. Did they forget to call ReceiveFinalityFlow? (com.r3.corda.lib.tokens.workflows.flows.rpc.MoveFungibleTokens is not registered)",
  "path": "/send"
}


Any idea for the reason ?

**Comment by kasiastreich** [comment]
Hi :) You need to annotate your flows with `@InitiatingFlow` if they are initiating. From the code snippet you pasted I guess that both of them are initiating (because they are startable via RPC). There is very good documentation on Corda flows:  https://docs.corda.net/api-flows.html Additionally, those kind of general questions are better asked on Slack, where people can answer them quicker.
Hope that helps!

**Comment by jarturocastan** [comment]
This code is funtional in 1.0 and i can start this vía RPC, why not in 1.1?

**Comment by manosbatsis** [comment]
@kasiastreich just in case: could a participant be "mistreated" if somehow added to the observer's list?

@jarturocastan code seems to have concerns mixed up a bit. You might want to try cordaledger.slack.com for help, although leaving the issue to read the docs or clear my head for a bit tends to work much better for me ;-)
