### ISSUE TITLE
RedeemFungibleToken issue

### ISSUE THREAD

**Issue by saraGeorge** [corda/token-sdk#175]
Hi,
I have created 2 accounts in node A.

I have issued 70 USD  to both accounts from node A.

However when I try to redeem token from first account (eg : 5 tokens) by explicitly specifying change holder attribute , redemption works the first time, however tokenHolder for remaining  65 units is changed to node A

Because of this redemption fails the second time as it explicitly checks for tokens held by the account.

Can somebody please explain what is going on in the above scenario? Is there anyway to mitigate this error and ensure that the tokens are indeed deducted from the expected accounts.

Thanks in advance

**Comment by adelRestom** [comment]
1. Request a new key for account A.
2. Use the returned key (the flow `RequestKeyForAccount` returns `AnonymousParty`); assigned the returned `AnonymousParty` as the change owner.
3. Please post your questions to cordaledger.slack.com or on StackOverlfow with tag Corda; the repository issues section is for reporting issues and improvements.

**Comment by sandramarianegeorge** [comment]
Hi,
I have used anonymous party key as changeHolder. I am getting the same error

**Comment by adelRestom** [comment]
Can help more without seeing your code really.

**Comment by saraGeorge** [comment]
I use the following code to transfer :

enforceIssuerAndTokenIdentifierCheck - query criteria checks for tokens belonging to account, checks for token Issuer and token identifier.

senderKey has been generated and stored using RequestKeyForAccount flow

`subFlow(new MoveFungibleTokens(partyAndAmountForToken, ImmutableList.of(), enforceIssuerAndTokenIdentifierCheck, senderKey));`


Above code identifies correct accounts and transfer was executed successfully multiple times

To redeem tokens I use :

`subFlow(new RedeemFungibleTokens(amount, tokenIssuer, ImmutableList.of(),enforceIssuerAndTokenIdentifierCheck, senderKey));`

The first redemption occurs correctly with token being selected from account. 

However on redemption, token holder becomes holder: "O=PartyA, L=London, C=GB", because which subsequent redemption attempts result in the following error : 'Insufficient spendable states identified'
