### ISSUE TITLE
The tokens-money module MUST NOT be fat-jarred into tokens-workflows!

### ISSUE THREAD

**Issue by chrisr3** [corda/token-sdk#193]
Contract verification in Corda works as follows:
- The CorDapps involved in a particular transaction are all loaded into `AttachmentStorage` and assigned an `AttachmentId`.
- A signed transaction contains a list of all of the `AttachmentId`s used to build it.
- Corda assembles all of the `AttachmentId`s inside an instance of `AttachmentsClassLoader`, which is a special "in memory" Java classloader. Corda then recreates the original `LedgerTransaction` object using classes from `AttachmentsClassLoader`, along with all of the `Contract` objects etc, and then invokes `LedgerTransaction.verify()`.

Any CorDapp not included in the signed transaction's list of attachments will therefore _not exist_ in `AttachmentsClassLoader`. This may result in `ClassNotFoundException` or `NoClassDefFoundError` if one of its classes is subsequently referenced when Corda tries to execute `LedgerTransaction.verify()`.

For _deterministic_ contract verifiaction, the attachments are assembled inside the DJVM instead of `AttachmentsClassLoader`, but otherwise the principle is exactly the same.

The `tokens-money` CorDapp can be used by `tokens-contracts` and _*must*_ therefore be loadable into `AttachmentsClassLoader`. It is also expected to be loadable into the DJVM because its project applies the `deterministic.gradle` script plugin. But now that it has been fat-jarred into `tokens-workflows`, the entire `tokens-workflows` CorDapp would need to be loaded into `AttachmentStorage`, along with all of its `FlowLogic<?>` classes which can _**never**_ be instantiated inside the DJVM.

Fat-jar `tokens-selection` if you must, but doing the same with `tokens-money` files against the architecture of contract verification in Corda 4.x.

**Comment by roastario** [comment]
This is actually a bug introduced by [this commit](https://github.com/corda/token-sdk/commit/93fb5e676851c4838cea1255b72c389f063c252e)

I'm going to unwind part of these changes to fix this.
