### ISSUE TITLE
Error with token sdk dependencies when deploying nodes in the kotlin cordapp template

### ISSUE THREAD

**Issue by lmarinl1** [corda/token-sdk#28]
I'm geting the following error when running deploy nodes in the kotlin cordapp template using the token template branch. I followed the instructions in this [README](https://github.com/corda/token-sdk/blob/master/README.md)

:contracts:compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':contracts:compileKotlin'.
> Could not resolve all files for configuration ':contracts:compileClasspath'.
   > Could not find com.r3.corda.sdk.token:token-sdk-contract:0.1.
     Searched in the following locations:
         https://jcenter.bintray.com/com/r3/corda/sdk/token/token-sdk-contract/0.1/token-sdk-contract-0.1.pom
         https://jcenter.bintray.com/com/r3/corda/sdk/token/token-sdk-contract/0.1/token-sdk-contract-0.1.jar
         https://repo.maven.apache.org/maven2/com/r3/corda/sdk/token/token-sdk-contract/0.1/token-sdk-contract-0.1.pom
         https://repo.maven.apache.org/maven2/com/r3/corda/sdk/token/token-sdk-contract/0.1/token-sdk-contract-0.1.jar
         https://ci-artifactory.corda.r3cev.com/artifactory/corda/com/r3/corda/sdk/token/token-sdk-contract/0.1/token-sdk-contract-0.1.pom
         https://ci-artifactory.corda.r3cev.com/artifactory/corda/com/r3/corda/sdk/token/token-sdk-contract/0.1/token-sdk-contract-0.1.jar
         https://ci-artifactory.corda.r3cev.com/artifactory/corda-dev/com/r3/corda/sdk/token/token-sdk-contract/0.1/token-sdk-contract-0.1.pom
         https://ci-artifactory.corda.r3cev.com/artifactory/corda-dev/com/r3/corda/sdk/token/token-sdk-contract/0.1/token-sdk-contract-0.1.jar
         https://jitpack.io/com/r3/corda/sdk/token/token-sdk-contract/0.1/token-sdk-contract-0.1.pom
         https://jitpack.io/com/r3/corda/sdk/token/token-sdk-contract/0.1/token-sdk-contract-0.1.jar
         file:/Users/estudiante/.m2/repository/com/r3/corda/sdk/token/token-sdk-contract/0.1/token-sdk-contract-0.1.pom
         file:/Users/estudiante/.m2/repository/com/r3/corda/sdk/token/token-sdk-contract/0.1/token-sdk-contract-0.1.jar
     Required by:
         project :contracts
   > Could not find com.r3.corda.sdk.token.modules:token-sdk-money:0.1.
     Searched in the following locations:
         https://jcenter.bintray.com/com/r3/corda/sdk/token/modules/token-sdk-money/0.1/token-sdk-money-0.1.pom
         https://jcenter.bintray.com/com/r3/corda/sdk/token/modules/token-sdk-money/0.1/token-sdk-money-0.1.jar
         https://repo.maven.apache.org/maven2/com/r3/corda/sdk/token/modules/token-sdk-money/0.1/token-sdk-money-0.1.pom
         https://repo.maven.apache.org/maven2/com/r3/corda/sdk/token/modules/token-sdk-money/0.1/token-sdk-money-0.1.jar
         https://ci-artifactory.corda.r3cev.com/artifactory/corda/com/r3/corda/sdk/token/modules/token-sdk-money/0.1/token-sdk-money-0.1.pom
         https://ci-artifactory.corda.r3cev.com/artifactory/corda/com/r3/corda/sdk/token/modules/token-sdk-money/0.1/token-sdk-money-0.1.jar
         https://ci-artifactory.corda.r3cev.com/artifactory/corda-dev/com/r3/corda/sdk/token/modules/token-sdk-money/0.1/token-sdk-money-0.1.pom
         https://ci-artifactory.corda.r3cev.com/artifactory/corda-dev/com/r3/corda/sdk/token/modules/token-sdk-money/0.1/token-sdk-money-0.1.jar
         https://jitpack.io/com/r3/corda/sdk/token/modules/token-sdk-money/0.1/token-sdk-money-0.1.pom
         https://jitpack.io/com/r3/corda/sdk/token/modules/token-sdk-money/0.1/token-sdk-money-0.1.jar
         file:/Users/estudiante/.m2/repository/com/r3/corda/sdk/token/modules/token-sdk-money/0.1/token-sdk-money-0.1.pom
         file:/Users/estudiante/.m2/repository/com/r3/corda/sdk/token/modules/token-sdk-money/0.1/token-sdk-money-0.1.jar
     Required by:
         project :contracts

**Comment by roger3cev** [comment]
Hi @lmarinl1 - I've fixed this and updated the token-template branch. Cheers
