### ISSUE TITLE
Does corda have a stable API or sdk for wallet handling and cash management?

### ISSUE THREAD

**Issue by navinthenapster** [corda/token-sdk#5]
If yes, can you recommend some

**Comment by roger3cev** [comment]
Hi @navinthenapster,

Sorry for the slow response - I neglected to look at the issues!

Not yet - this is on the roadmap. The idea will be for clients to generate public /private key pairs, then share the public key with the node they wish to use. Signing will be done client side. The effect is that users have control over their states.

Can you be more specific around what you need for "cash management"? Thanks

Cheers

**Comment by zeddari** [comment]
Hi all
I'am using corda blockchain and I want to confirm that we can create wallet and send transaction inside this blockchain ?
