### ISSUE TITLE
[question] I couldn't find the design doc for this. can someone please point it to me. 

### ISSUE THREAD

**Issue by kid101** [corda/token-sdk#8]

**Comment by manosbatsis** [comment]
+1 on adding more documentation and/or a sample app using the SDK, would also make it easier for others to pitch in ;-)

**Comment by roger3cev** [comment]
Sure, sorry guys...!!!

There is a design doc in the corda repo [here](https://github.com/corda/corda/blob/rog-tokens-design-doc/docs/source/design/tokens/design.md).

It needs updating but the basic concepts are still the same. 

I'll be adding more docs ASAP. You are all more than welcome to pitch in as well! @illoyd is also going to have a crack at some docs - so maybe catch up with him on the Corda slack. 

Cheers!

**Comment by roger3cev** [comment]
Am I OK to close this one? Cheers

**Comment by kid101** [comment]
Yup

**Comment by roger3cev** [comment]
Cheers!
